import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// ヘッダーとフッターをインポート
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Live Navi App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex min-h-full flex-col bg-[#7d99a6] text-white antialiased`}
      >
        {/* 共通ヘッダー */}
        <Header />

        {/* メインコンテンツ */}
        <div className="flex flex-1 flex-col">{children}</div>

        {/* 共通フッター */}
        <Footer />
      </body>
    </html>
  );
}
